package com.peruzal.weather.models;

public class Forecast {
    public double apparentTemperatureHigh;
    public int apparentTemperatureHighTime;
    public double apparentTemperatureLow;
    public int apparentTemperatureLowTime;
    public double apparentTemperatureMax;
    public int apparentTemperatureMaxTime;
    public double apparentTemperatureMin;
    public int apparentTemperatureMinTime;
    public double cloudCover;
    public double dewPoint;
    public double humidity;
    public String icon;
    public double moonPhase;
    public double ozone;
    public double precipIntensity;
    public double precipIntensityMax;
    public int precipIntensityMaxTime;
    public double precipProbability;
    public String precipType;
    public double pressure;
    public String summary;
    public int sunriseTime;
    public int sunsetTime;
    public double temperatureHigh;
    public int temperatureHighTime;
    public double temperatureLow;
    public int temperatureLowTime;
    public double temperatureMax;
    public int temperatureMaxTime;
    public double temperatureMin;
    public int temperatureMinTime;
    public int time;
    public int uvIndex;
    public int uvIndexTime;
    public double visibility;
    public int windBearing;
    public double windGust;
    public int windGustTime;
    public double windSpeed;
}
