package com.peruzal.weather.models;

public enum WeatherError  {
    NETWORK_UNAVAILABLE,
    INTERRUPTED,
    GENERAL_FAILURE,
    DATA_FAILURE,
    LOCATION_PERMISSED_DENIED,
    JSON_DATA_PARSE_ERROR, LOCATION_UNAVAILABLE
}
